name: Keep Render Service Alive

on:
  schedule:
    # Ping every 10 minutes (adjust as needed)
    - cron: '*/10 * * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    
    steps:
    - name: Ping Render Service
      run: |
        # Replace YOUR_RENDER_URL with your actual Render URL
        curl -f https:/https://college-library-system.onrender.com|| echo "Service might be starting up"
        
    - name: Wait and ping again
      run: |
        sleep 30
        curl -f https://https://college-library-system.onrender.com || echo "Second ping completed"
